/**
 * Parse a Matrix-exported Realcomp CSV into normalized listing rows.
 * Used by both the client-side import UI and the server-side webhook that
 * receives Cloudmailin email forwards from Matrix scheduled-email exports.
 */

export function parseRealcompCSV(text) {
  const lines = text.split(/\r?\n/).filter((l) => l.trim());
  if (lines.length < 2) return [];

  // Heuristic: first non-empty line that has multiple commas is the header
  // (Matrix sometimes prepends "Generated by Matrix..." lines)
  let headerIdx = 0;
  for (let i = 0; i < Math.min(5, lines.length); i++) {
    if ((lines[i].match(/,/g) || []).length >= 4) { headerIdx = i; break; }
  }
  const headers = lines[headerIdx]
    .split(',')
    .map((h) => h.replace(/^"|"$/g, '').trim().toLowerCase());

  const get = (row, ...keys) => {
    for (const k of keys) {
      const i = headers.findIndex((h) => h.includes(k));
      if (i !== -1 && row[i] !== undefined && row[i] !== null) {
        return String(row[i]).replace(/^"|"$/g, '').trim();
      }
    }
    return '';
  };

  return lines.slice(headerIdx + 1).map((line, idx) => {
    const row =
      line.match(/(".*?"|[^,]+|(?<=,)(?=,)|^(?=,)|(?<=,)$)/g) ||
      line.split(',');
    return {
      // Stable id based on MLS#. Falls back to row index so rows without
      // MLS# still get a unique id.
      mlsNum:    get(row, 'mls#', 'mls #', 'listing id', 'list num', 'ml#'),
      address:   get(row, 'address', 'street'),
      city:      get(row, 'city'),
      zip:       get(row, 'zip', 'postal'),
      status:    get(row, 'status', 'listing status'),
      listPrice: get(row, 'list price', 'listing price', 'orig price'),
      salePrice: get(row, 'sale price', 'sold price', 'close price', 'sold amt'),
      beds:      get(row, 'bed', 'br'),
      baths:     get(row, 'bath', 'ba'),
      sqft:      get(row, 'sqft', 'sq ft', 'square feet', 'approx sqft'),
      dom:       get(row, 'dom', 'days on market'),
      listDate:  get(row, 'list date', 'listing date'),
      closeDate: get(row, 'close date', 'sold date', 'closing date'),
      agent:     get(row, 'list agent', 'agent name', 'agent'),
      _row:      idx,
    };
  }).filter((r) => r.address || r.mlsNum);
}

// Helper to coerce CSV string values into the numeric / date types our
// listings table expects.
export function toDbRow(r, userId) {
  const num = (v) => {
    if (v === '' || v == null) return null;
    const n = Number(String(v).replace(/[^0-9.-]/g, ''));
    return Number.isFinite(n) ? n : null;
  };
  const int = (v) => {
    const n = num(v);
    return n == null ? null : Math.round(n);
  };
  const date = (v) => {
    if (!v) return null;
    const d = new Date(v);
    return isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10);
  };
  return {
    id: `rc_${userId.slice(0, 8)}_${r.mlsNum || `noml_${r._row}_${Date.now()}`}`,
    user_id: userId,
    mls_num: r.mlsNum || null,
    address: r.address || '',
    city: r.city || '',
    zip: r.zip || '',
    status: r.status || '',
    list_price: num(r.listPrice),
    sale_price: num(r.salePrice),
    beds: int(r.beds),
    baths: num(r.baths),
    sqft: int(r.sqft),
    dom: int(r.dom),
    list_date: date(r.listDate),
    close_date: date(r.closeDate),
    agent: r.agent || '',
    meta: {},
  };
}
